BEGIN TRANSACTION;
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (1,'mclaren','McLaren','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (2,'bmw_sauber','BMW Sauber','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (3,'williams','Williams','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (4,'renault','Renault','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (5,'toro_rosso','Toro Rosso','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (6,'ferrari','Ferrari','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (7,'toyota','Toyota','Japanese');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (8,'super_aguri','Super Aguri','Japanese');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (9,'red_bull','Red Bull','Austrian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (10,'force_india','Force India','Indian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (11,'honda','Honda','Japanese');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (12,'spyker','Spyker','Dutch');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (13,'mf1','MF1','Russian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (14,'spyker_mf1','Spyker MF1','Dutch');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (15,'sauber','Sauber','Swiss');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (16,'bar','BAR','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (17,'jordan','Jordan','Irish');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (18,'minardi','Minardi','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (19,'jaguar','Jaguar','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (20,'prost','Prost','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (21,'arrows','Arrows','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (22,'benetton','Benetton','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (23,'brawn','Brawn','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (24,'stewart','Stewart','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (25,'tyrrell','Tyrrell','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (26,'lola','Lola','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (27,'ligier','Ligier','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (28,'forti','Forti','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (29,'footwork','Footwork','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (30,'pacific','Pacific','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (31,'simtek','Simtek','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (32,'team_lotus','Team Lotus','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (33,'larrousse','Larrousse','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (34,'brabham','Brabham','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (35,'dallara','Dallara','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (36,'fondmetal','Fondmetal','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (37,'march','March','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (38,'moda','Andrea Moda','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (39,'ags','AGS','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (40,'lambo','Lambo','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (41,'leyton','Leyton House','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (42,'coloni','Coloni','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (44,'eurobrun','Euro Brun','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (45,'osella','Osella','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (46,'onyx','Onyx','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (47,'life','Life','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (48,'rial','Rial','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (49,'zakspeed','Zakspeed','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (50,'ram','RAM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (51,'alfa','Alfa Romeo','Swiss');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (52,'spirit','Spirit','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (53,'toleman','Toleman','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (54,'ats','ATS','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (55,'theodore','Theodore','Hong Kong');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (56,'fittipaldi','Fittipaldi','Brazilian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (57,'ensign','Ensign','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (58,'shadow','Shadow','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (59,'wolf','Wolf','Canadian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (60,'merzario','Merzario','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (61,'kauhsen','Kauhsen','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (62,'rebaque','Rebaque','Mexican');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (63,'surtees','Surtees','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (64,'hesketh','Hesketh','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (65,'martini','Martini','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (66,'brm','BRM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (67,'penske','Penske','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (68,'lec','LEC','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (69,'mcguire','McGuire','Australian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (70,'boro','Boro','Dutch');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (71,'apollon','Apollon','Swiss');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (72,'kojima','Kojima','Japanese');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (73,'parnelli','Parnelli','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (74,'maki','Maki','Japanese');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (75,'hill','Embassy Hill','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (76,'lyncar','Lyncar','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (77,'trojan','Trojan','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (78,'amon','Amon','New Zealander');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (79,'token','Token','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (80,'iso_marlboro','Iso Marlboro','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (81,'tecno','Tecno','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (82,'matra','Matra','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (83,'politoys','Politoys','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (84,'connew','Connew','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (85,'bellasi','Bellasi','Swiss');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (86,'tomaso','De Tomaso','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (87,'cooper','Cooper','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (88,'eagle','Eagle','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (89,'lds','LDS','South African');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (90,'protos','Protos','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (91,'shannon','Shannon','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (92,'scirocco','Scirocco','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (93,'re','RE','Rhodesian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (94,'brp','BRP','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (95,'porsche','Porsche','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (96,'derrington','Derrington','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (97,'gilby','Gilby','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (98,'stebro','Stebro','Canadian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (99,'emeryson','Emeryson','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (100,'enb','ENB','Belgian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (101,'jbw','JBW','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (102,'ferguson','Ferguson','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (103,'mbm','MBM','Swiss');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (104,'behra-porsche','Behra-Porsche','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (105,'maserati','Maserati','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (106,'scarab','Scarab','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (107,'watson','Watson','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (108,'epperly','Epperly','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (109,'phillips','Phillips','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (110,'lesovsky','Lesovsky','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (111,'trevis','Trevis','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (112,'meskowski','Meskowski','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (113,'kurtis_kraft','Kurtis Kraft','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (114,'kuzma','Kuzma','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (115,'vhristensen','Christensen','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (116,'ewing','Ewing','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (117,'aston_martin','Aston Martin','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (118,'vanwall','Vanwall','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (119,'moore','Moore','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (120,'dunn','Dunn','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (121,'elder','Elder','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (122,'sutton','Sutton','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (123,'fry','Fry','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (124,'tec-mec','Tec-Mec','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (125,'connaught','Connaught','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (126,'alta','Alta','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (127,'osca','OSCA','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (128,'gordini','Gordini','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (129,'stevens','Stevens','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (130,'bugatti','Bugatti','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (131,'mercedes','Mercedes','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (132,'lancia','Lancia','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (133,'hwm','HWM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (134,'schroeder','Schroeder','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (135,'pawl','Pawl','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (136,'pankratz','Pankratz','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (137,'arzani-volpini','Arzani-Volpini','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (138,'nichels','Nichels','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (139,'bromme','Bromme','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (140,'klenk','Klenk','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (141,'simca','Simca','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (142,'turner','Turner','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (143,'del_roy','Del Roy','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (144,'veritas','Veritas','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (145,'bmw','BMW','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (146,'emw','EMW','East German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (147,'afm','AFM','German');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (148,'frazer_nash','Frazer Nash','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (149,'sherman','Sherman','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (150,'deidt','Deidt','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (151,'era','ERA','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (152,'butterworth','Aston Butterworth','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (153,'cisitalia','Cisitalia','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (154,'lago','Talbot-Lago','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (155,'hall','Hall','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (156,'marchese','Marchese','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (157,'langley','Langley','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (158,'rae','Rae','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (159,'olson','Olson','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (160,'wetteroth','Wetteroth','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (161,'adams','Adams','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (162,'snowberger','Snowberger','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (163,'milano','Milano','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (164,'hrt','HRT','Spanish');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (166,'virgin','Virgin','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (167,'cooper-maserati','Cooper-Maserati','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (168,'cooper-osca','Cooper-OSCA','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (169,'cooper-borgward','Cooper-Borgward','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (170,'cooper-climax','Cooper-Climax','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (171,'cooper-castellotti','Cooper-Castellotti','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (172,'lotus-climax','Lotus-Climax','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (173,'lotus-maserati','Lotus-Maserati','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (174,'de_tomaso-osca','De Tomaso-Osca','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (175,'de_tomaso-alfa_romeo','De Tomaso-Alfa Romeo','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (176,'lotus-brm','Lotus-BRM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (177,'lotus-borgward','Lotus-Borgward','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (178,'cooper-alfa_romeo','Cooper-Alfa Romeo','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (179,'de_tomaso-ferrari','De Tomaso-Ferrari','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (180,'lotus-ford','Lotus-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (181,'brabham-brm','Brabham-BRM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (182,'brabham-ford','Brabham-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (183,'brabham-climax','Brabham-Climax','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (184,'lds-climax','LDS-Climax','South African');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (185,'lds-alfa_romeo','LDS-Alfa Romeo','South African');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (186,'cooper-ford','Cooper-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (187,'mclaren-ford','McLaren-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (188,'mclaren-seren','McLaren-Serenissima','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (189,'eagle-climax','Eagle-Climax','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (190,'eagle-weslake','Eagle-Weslake','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (191,'brabham-repco','Brabham-Repco','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (192,'cooper-ferrari','Cooper-Ferrari','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (193,'cooper-ats','Cooper-ATS','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (194,'mclaren-brm','McLaren-BRM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (195,'cooper-brm','Cooper-BRM','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (196,'matra-ford','Matra-Ford','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (197,'brm-ford','BRM-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (198,'mclaren-alfa_romeo','McLaren-Alfa Romeo','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (199,'march-alfa_romeo','March-Alfa Romeo','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (200,'march-ford','March-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (201,'lotus-pw','Lotus-Pratt & Whitney','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (202,'shadow-ford','Shadow-Ford','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (203,'shadow-matra','Shadow-Matra','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (204,'brabham-alfa_romeo','Brabham-Alfa Romeo','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (205,'lotus_racing','Lotus','Malaysian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (206,'marussia','Marussia','Russian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (207,'caterham','Caterham','Malaysian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (208,'lotus_f1','Lotus F1','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (209,'manor','Manor Marussia','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (210,'haas','Haas F1 Team','American');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (211,'racing_point','Racing Point','British');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (213,'alphatauri','AlphaTauri','Italian');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (214,'alpine','Alpine F1 Team','French');
INSERT INTO "constructors" ("constructorId","constructorRef","name","nationality") VALUES (215,'rb','RB F1 Team','Italian');
COMMIT;
